apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ops-kubernetes-dev-slack-webhook-url
  namespace: ops
  labels:
    app.kubernetes.io/name: slack-webhook-url
    app.kubernetes.io/instance: ops-kubernetes-dev
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: ops
    app.kubernetes.io/managed-by: fluxcd
    app.hobsons.io/env-name: dev
    app.hobsons.io/env-type: dev
    app.hobsons.io/product-line: platform
    app.hobsons.io/product-component: k8s
    app.hobsons.io/provisioner: fluxcd
    app.hobsons.io/owner-contact: dl-platform-k8s
    app.hobsons.io/maintenance-contact: dl-platform-k8s
spec:
  backendType: secretsManager
  data:
    - key: tf-platform-k8s-dev/ops/aws-node-termination-handler/slack-webhook-url
      name: address
      property: address
