apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ops
resources:
  - ../../../bases/weavescope
  - ../../../bases/weavescope-brkt
patchesStrategicMerge:
  - deployment-env.yaml
  - ds-bkrt-env.yaml
