apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: ops
  labels:
    app.kubernetes.io/name: fluent-bit-config
    app.kubernetes.io/instance: fluent-bit-config-ops
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: fluxcd
    app.hobsons.io/env-name: dev
    app.hobsons.io/env-type: dev
    app.hobsons.io/product-line: platform
    app.hobsons.io/product-component: logging
    app.hobsons.io/provisioner: k8s
    app.hobsons.io/owner-contact: dl-cloudops
    app.hobsons.io/maintenance-contact: dl-cloudops
data:
  fluent-bit-service.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    warn
        Parsers_File parsers.conf

  fluent-bit-input.conf: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Exclude_Path     /var/log/containers/*_ops_*.log,/var/log/containers/*_kube-*_*.log
        Parser           cri
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    10MB
        Skip_Long_Lines  On
        Ignore_Older     60m

  fluent-bit-filter.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  fluent-bit-output.conf: |
    [OUTPUT]
        Name            null
        Match           *

  fluent-bit.conf: |
    @INCLUDE fluent-bit-service.conf
    @INCLUDE fluent-bit-input.conf
    @INCLUDE fluent-bit-filter.conf
    @INCLUDE fluent-bit-output.conf

  parsers.conf: |
