apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: ops
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-ops
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: fluxcd
    app.hobsons.io/env-name: dev
    app.hobsons.io/env-type: dev
    app.hobsons.io/product-line: platform
    app.hobsons.io/product-component: logging
    app.hobsons.io/provisioner: k8s
    app.hobsons.io/owner-contact: dl-cloudops
    app.hobsons.io/maintenance-contact: dl-cloudops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/instance: fluent-bit-ops
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/instance: fluent-bit-ops
        app.kubernetes.io/component: logging
        app.kubernetes.io/part-of: platform
        app.kubernetes.io/managed-by: fluxcd
        app.hobsons.io/env-name: dev
        app.hobsons.io/env-type: dev
        app.hobsons.io/product-line: platform
        app.hobsons.io/product-component: logging
        app.hobsons.io/provisioner: k8s
        app.hobsons.io/owner-contact: dl-cloudops
        app.hobsons.io/maintenance-contact: dl-cloudops
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirst
      serviceAccountName: fluent-bit-service-account
      containers:
        - name: fluent-bit
          image: "fluent/fluent-bit:1.8.6"
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 16Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit-service.conf
              subPath: fluent-bit-service.conf
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit-input.conf
              subPath: fluent-bit-input.conf
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit-filter.conf
              subPath: fluent-bit-filter.conf
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit-output.conf
              subPath: fluent-bit-output.conf
      terminationGracePeriodSeconds: 10
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: fluent-bit-config
