apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ops
  labels:
    app.kubernetes.io/name: fluent-bit-service-account
    app.kubernetes.io/instance: fluent-bit-service-account-ops
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: fluxcd
    app.hobsons.io/env-name: dev
    app.hobsons.io/env-type: dev
    app.hobsons.io/product-line: platform
    app.hobsons.io/product-component: logging
    app.hobsons.io/provisioner: k8s
    app.hobsons.io/owner-contact: dl-cloudops
    app.hobsons.io/maintenance-contact: dl-cloudops
  name: fluent-bit-service-account
