# borrowed from https://cloud.weave.works/k8s/scope.yaml?k8s-version=1.9.3
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weave-scope-agent-bottlerocket
  labels:
    name: weave-scope-agent-bottlerocket
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: agent
  namespace: weave
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: weave-scope
      name: weave-scope-agent-bottlerocket
  template:
    metadata:
      labels:
        name: weave-scope-agent-bottlerocket
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: os-type
                operator: In
                values:
                - bottlerocket
      containers:
        - name: scope-agent
          args:
            - '--mode=probe'
            - '--probe-only'
            - '--probe.kubernetes.role=host'
            - '--probe.docker.bridge=docker0'
            - '--probe.docker=false'
            - '--probe.ebpf.connections=false'
            - '--probe.cri=true'
            - '--probe.cri.endpoint=unix:///run/dockershim.sock'
            - '--weave=false'
            - '--probe.no-controls=true'
            - 'weave-scope-app.ops.svc.cluster.local.:80'
          env:
          - name: CHECKPOINT_DISABLE
            value: "true"
          image: weaveworks/scope:1.12.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 150Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: cri-socket
              mountPath: /run/dockershim.sock
              readOnly: true
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
              readOnly: true
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      tolerations:
      - operator: Exists
      volumes:
        - name: cri-socket
          hostPath:
            path: /run/dockershim.sock
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
