apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "ops"
resources:
- ../../../bases/ops-apps-shared-ingress
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ops-apps
  path: ./shared-ingress.yaml
- target:
    group: kubernetes-client.io
    version: v1
    kind: ExternalSecret
    name: apps-ops-k8s-oidc
  path: ./external-secret.yaml
